# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 365
# Issues with these labels will never be considered stale
exemptLabels:
  - high priority
  - new feature
  - bug
  - discussion
# Label to use when marking an issue as stale
staleLabel: 'wontfix'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi there 👋🏼!

  This issue has gone quiet 😶.

  We currently close issues after 365 days of inactivity. It's been at least 180 days since the last update here.
  If we missed this issue or if you want to keep it open, please reply here. You can also add or suggest the label "discussion" to keep this issue open!
  As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. 
  Check out our [Contribution Guidelines](https://github.com/abapm/abappm/blob/main/CONTRIBUTING.md) for more information about opening PRs, triaging issues, and contributing!

  Thanks for being a part of the apm community! 💘
  
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
